### PR TITLE
Version 1.1.0: Apis Update and Documentation Improvements

### PR DESCRIPTION
**Pull request by Usama-Azad**
This merge includes changes for version 1.1.0, which brings significant enhancements and documentation improvements. It updates deprecated APIs to align with Paymob's latest standards and includes detailed documentation for the public APIs. This version is now in sync with the new API reference available at https://docs.paymob.pk/docs/accept-standard-redirect

### CODE REVIEW

**Comment by arshmancodes** [comment]
Thank you for the Contribution! @Usama-Azad .

I'll have a look at the Updates, Can you make sure to Update the Readme.MD with the ChangeLog? so that The changes could be visibly seen on Pub.dev too.

**Comment by Usama-Azad** [comment]
README.md Updated.

**Comment by arshmancodes** [comment]
@Usama-Azad  I respect you contribution to the Code, but the Base URL you have changed is not for Paymob Pakistan, 
Pakistani Paymob Account holders are not able to get Authorised from the Global API Endpoint. 

Somethings i would like to add over here are.

- Make sure to add a Valuable Contribution.
- Adding Value to the code is the Main concern not the Lines of Codes added.
- I have reviewed all the files and the only thing that is valuable is the _getIntegrationIdbyPaymentType.
- I appreciate the approach for this but all the other code refactorings seems a bit useless, just reordering the Function Parameters.

I hope you would understand the point.

Anyways Thank you for the contribution and Keep contributing 🚀

**Comment by Usama-Azad** [comment]
I was working on an app where I needed to integrate a payment gateway. When I used your package, it was throwing a strange error, causing the app to crash. However, I was able to fix this issue, and in my latest update, the app no longer crashes and is functioning properly.

Secondly, I have updated to the latest dependencies.

Thirdly, I noticed that the public APIs' documentation was not showing in my code editor. I had to manually refer to the package files. I have now added the documentation to the project.

I only intended to integrate the package, and if there were no issues, I wouldn't have needed to go out of my way to resolve them. It took me a significant amount of time to fix these issues.

Furthermore, I wasn't aware of the differences in APIs for Pakistan, so I apologize for any oversight, and I have also fixed that.

I hope this clarifies the situation.

**Pull request closed without merging**
